/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AreaRouteImport } from './routes/area'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAtivosRouteImport } from './routes/admin.ativos'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminConsultasRouteImport } from './routes/admin.consultas'
import { Route as AdminDevelopmentRouteImport } from './routes/admin.development'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminFipeRouteImport } from './routes/admin.fipe'
import { Route as AdminFlowsRouteImport } from './routes/admin.flows'
import { Route as AdminTiposRouteImport } from './routes/admin.tipos'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AreaIndexRouteImport } from './routes/area.index'
import { Route as AreaCardsRouteImport } from './routes/area.cards'
import { Route as AreaConsultasRouteImport } from './routes/area.consultas'
import { Route as AreaPerfilRouteImport } from './routes/area.perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaRoute = AreaRouteImport.update({
  id: '/area',
  path: '/area',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtivosRoute = AdminAtivosRouteImport.update({
  id: '/ativos',
  path: '/ativos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultasRoute = AdminConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevelopmentRoute = AdminDevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFipeRoute = AdminFipeRouteImport.update({
  id: '/fipe',
  path: '/fipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlowsRoute = AdminFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTiposRoute = AdminTiposRouteImport.update({
  id: '/tipos',
  path: '/tipos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AreaIndexRoute = AreaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AreaRoute,
} as any)
const AreaCardsRoute = AreaCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AreaRoute,
} as any)
const AreaConsultasRoute = AreaConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => AreaRoute,
} as any)
const AreaPerfilRoute = AreaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AreaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/area': typeof AreaRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/ativos': typeof AdminAtivosRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/consultas': typeof AdminConsultasRoute
  '/admin/development': typeof AdminDevelopmentRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/fipe': typeof AdminFipeRoute
  '/admin/flows': typeof AdminFlowsRoute
  '/admin/tipos': typeof AdminTiposRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/area/cards': typeof AreaCardsRoute
  '/area/consultas': typeof AreaConsultasRoute
  '/area/perfil': typeof AreaPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/area/': typeof AreaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/ativos': typeof AdminAtivosRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/consultas': typeof AdminConsultasRoute
  '/admin/development': typeof AdminDevelopmentRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/fipe': typeof AdminFipeRoute
  '/admin/flows': typeof AdminFlowsRoute
  '/admin/tipos': typeof AdminTiposRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/area/cards': typeof AreaCardsRoute
  '/area/consultas': typeof AreaConsultasRoute
  '/area/perfil': typeof AreaPerfilRoute
  '/admin': typeof AdminIndexRoute
  '/area': typeof AreaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/area': typeof AreaRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/ativos': typeof AdminAtivosRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/consultas': typeof AdminConsultasRoute
  '/admin/development': typeof AdminDevelopmentRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/fipe': typeof AdminFipeRoute
  '/admin/flows': typeof AdminFlowsRoute
  '/admin/tipos': typeof AdminTiposRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/area/cards': typeof AreaCardsRoute
  '/area/consultas': typeof AreaConsultasRoute
  '/area/perfil': typeof AreaPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/area/': typeof AreaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/area'
    | '/dashboard'
    | '/pricing'
    | '/admin/analytics'
    | '/admin/ativos'
    | '/admin/audit'
    | '/admin/consultas'
    | '/admin/development'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/fipe'
    | '/admin/flows'
    | '/admin/tipos'
    | '/admin/usuarios'
    | '/area/cards'
    | '/area/consultas'
    | '/area/perfil'
    | '/admin/'
    | '/area/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/pricing'
    | '/admin/analytics'
    | '/admin/ativos'
    | '/admin/audit'
    | '/admin/consultas'
    | '/admin/development'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/fipe'
    | '/admin/flows'
    | '/admin/tipos'
    | '/admin/usuarios'
    | '/area/cards'
    | '/area/consultas'
    | '/area/perfil'
    | '/admin'
    | '/area'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/area'
    | '/dashboard'
    | '/pricing'
    | '/admin/analytics'
    | '/admin/ativos'
    | '/admin/audit'
    | '/admin/consultas'
    | '/admin/development'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/fipe'
    | '/admin/flows'
    | '/admin/tipos'
    | '/admin/usuarios'
    | '/area/cards'
    | '/area/consultas'
    | '/area/perfil'
    | '/admin/'
    | '/area/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AreaRoute: typeof AreaRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area': {
      id: '/area'
      path: '/area'
      fullPath: '/area'
      preLoaderRoute: typeof AreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ativos': {
      id: '/admin/ativos'
      path: '/ativos'
      fullPath: '/admin/ativos'
      preLoaderRoute: typeof AdminAtivosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultas': {
      id: '/admin/consultas'
      path: '/consultas'
      fullPath: '/admin/consultas'
      preLoaderRoute: typeof AdminConsultasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/development': {
      id: '/admin/development'
      path: '/development'
      fullPath: '/admin/development'
      preLoaderRoute: typeof AdminDevelopmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fipe': {
      id: '/admin/fipe'
      path: '/fipe'
      fullPath: '/admin/fipe'
      preLoaderRoute: typeof AdminFipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flows': {
      id: '/admin/flows'
      path: '/flows'
      fullPath: '/admin/flows'
      preLoaderRoute: typeof AdminFlowsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tipos': {
      id: '/admin/tipos'
      path: '/tipos'
      fullPath: '/admin/tipos'
      preLoaderRoute: typeof AdminTiposRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/area/': {
      id: '/area/'
      path: '/'
      fullPath: '/area/'
      preLoaderRoute: typeof AreaIndexRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area/cards': {
      id: '/area/cards'
      path: '/cards'
      fullPath: '/area/cards'
      preLoaderRoute: typeof AreaCardsRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area/consultas': {
      id: '/area/consultas'
      path: '/consultas'
      fullPath: '/area/consultas'
      preLoaderRoute: typeof AreaConsultasRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area/perfil': {
      id: '/area/perfil'
      path: '/perfil'
      fullPath: '/area/perfil'
      preLoaderRoute: typeof AreaPerfilRouteImport
      parentRoute: typeof AreaRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAtivosRoute: typeof AdminAtivosRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminConsultasRoute: typeof AdminConsultasRoute
  AdminDevelopmentRoute: typeof AdminDevelopmentRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminFipeRoute: typeof AdminFipeRoute
  AdminFlowsRoute: typeof AdminFlowsRoute
  AdminTiposRoute: typeof AdminTiposRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAtivosRoute: AdminAtivosRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminConsultasRoute: AdminConsultasRoute,
  AdminDevelopmentRoute: AdminDevelopmentRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminFipeRoute: AdminFipeRoute,
  AdminFlowsRoute: AdminFlowsRoute,
  AdminTiposRoute: AdminTiposRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AreaRouteChildren {
  AreaCardsRoute: typeof AreaCardsRoute
  AreaConsultasRoute: typeof AreaConsultasRoute
  AreaPerfilRoute: typeof AreaPerfilRoute
  AreaIndexRoute: typeof AreaIndexRoute
}

const AreaRouteChildren: AreaRouteChildren = {
  AreaCardsRoute: AreaCardsRoute,
  AreaConsultasRoute: AreaConsultasRoute,
  AreaPerfilRoute: AreaPerfilRoute,
  AreaIndexRoute: AreaIndexRoute,
}

const AreaRouteWithChildren = AreaRoute._addFileChildren(AreaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AreaRoute: AreaRouteWithChildren,
  DashboardRoute: DashboardRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
